Data Analytics - 21/22 
---------------
``` 
> Utrecht University
> Michael Behrisch
```

---

Python Tutorial - Numpy and Pandas
---------------

```
> Instead of reading a static tutorial we will work and execute code to learn and explore Python concepts. 
```
The example form below are adapted from _Lectures on scientific computing with Python_ by _jrjohansson_ and _Mark Bakker_ from _TU Delft_

---

#### Numpy 
The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is array.

__Why Numpy__

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).

In [1]:
import numpy as np

```
> Create numpy arrays 
```

In [2]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [3]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2,0], [3, 4, 3]])

M

array([[1, 2, 0],
       [3, 4, 3]])

```
> The difference between the v and M arrays is only their shapes. We can get information about the shape of an array by using the ndarray.shape property
```

In [7]:
v.shape

(4,)

In [8]:
M.shape

(2, 3)

```
> Using array-generating functions
```

In [9]:
# create a range

x = np.arange(0, 10, 1) # arguments: start, stop, step

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x = np.diag([1,2,3])

x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
M = np.random.rand(3,3)

M

array([[0.1302241 , 0.16422491, 0.46534991],
       [0.10309861, 0.05011615, 0.0312009 ],
       [0.20966147, 0.34058865, 0.42513088]])

```
> Manipulating arrays 
```

In [12]:
# v is a vector, and has only one dimension, taking one index
v[0]

1

In [13]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M[1,1]

0.050116148712487485

In [14]:
M[1]

array([0.10309861, 0.05011615, 0.0312009 ])

In [15]:
M[1,:] # row 1

array([0.10309861, 0.05011615, 0.0312009 ])

In [16]:
M[:,1] # column 1

array([0.16422491, 0.05011615, 0.34058865])

```
> Assign new values 
```

In [15]:
M[0,0] = 1

M

array([[1.        , 0.02662682, 0.42268433],
       [0.82222003, 0.19749464, 0.9350836 ],
       [0.37151601, 0.05565477, 0.00576601]])

```
> Index slicing
```

In [16]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [17]:
A[1:3]

array([2, 3])

In [20]:
A[:3] # first three elements

array([1, 2, 3])

In [21]:
A[-1] # the last element in the array

5

```
> More on indexing 
```

In [22]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [23]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

```
> Array operations 
```

In [24]:
A.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

In [25]:
np.diag(A)

array([ 0, 11, 22, 33, 44])

```
> There are more array operations ...
```

#### Linear algebra in numpy

In [26]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [27]:
v1 * 2

array([0, 2, 4, 6, 8])

In [28]:
v1 + 2

array([2, 3, 4, 5, 6])

In [29]:
v1 * v1 # element-wise multiplication

array([ 0,  1,  4,  9, 16])

```
> Matrix mutiplication
```

In [30]:
np.dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

```
> There are more array operations ...
```

```
> Data processing
```

In [31]:
np.shape(A)

(5, 5)

In [32]:
np.mean(A) # Mean values

22.0

In [33]:
# Minimum  
A.min()

0

In [34]:
# Maximum 
A.max()

44

In [35]:
# Sum 
np.sum(A)

550

```
> Stacking
```

In [36]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [37]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

```
> Copy and DEEP COPY 
```

In [39]:
A = np.array([[1, 2], [3, 4]])

A

array([[1, 2],
       [3, 4]])

In [40]:
# now B is referring to the same array data as A 
B = A

In [41]:
# changing B affects A
B[0,0] = 10

B

array([[10,  2],
       [ 3,  4]])

In [42]:
A

array([[10,  2],
       [ 3,  4]])

```
> How to make a deep copy 
```

In [43]:
B = np.copy(A)

In [44]:
# now, if we modify B, A is not affected
B[0,0] = -5

B

array([[-5,  2],
       [ 3,  4]])

In [45]:
A

array([[10,  2],
       [ 3,  4]])

```
> Iterating over array elements 
```

In [46]:
v = np.array([1,2,3,4])

for element in v:
    print(element)

1
2
3
4

#### There are a huge list of functions already implemented in `numpy` - see Documentation: https://docs.scipy.org/doc/numpy-1.16.1/user/quickstart.html

---
---
## Your 5. Task
```
> Create a integer array from a range between 100 - 300. The difference between the elements should be 10. 
```

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220,
       230, 240, 250, 260, 270, 280, 290])

---
---
## Your 6. Task
```
> Delete the second column of the numpy array arr_1 and insert the new column arr_2 in its place.
```

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

---
---

### Pandas

```
> Data is often stored in CSV files (Comma Separated Values, although the values can be separated by other things than commas)
> The most powerful and advanced package for data handling and analysis is called pandas.
```

In [26]:
import pandas as pd

```
> Load Iris dataset 
```

In [27]:
iris = pd.read_csv('iris.csv')
print(iris)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [28]:
# Print first 5 lines of Data Frame 
print(iris.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

```
> Basic DataFrame maniupulation 
```

In [35]:
print('Names of columns:')
print(iris.keys())
for key in iris.keys():
    print(key)

Names of columns:
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
sepal_length
sepal_width
petal_length
petal_width
species

In [36]:
# .iloc stands for index location
print(iris.iloc[0, 0])

5.1

In [37]:
print(iris.iloc[1, 0])

4.9

In [32]:
print(iris.iloc[2, 2])

1.3

In [33]:
print(iris.iloc[3])

sepal_length            4.6
sepal_width             3.1
petal_length            1.5
petal_width             0.2
species         Iris-setosa
Name: 3, dtype: object

In [41]:
print(iris.iloc[:, 1])

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [57]:
iris['sepal_width']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [58]:
# add another column 
iris.insert(1, 'copy_sepal_width', iris['sepal_width'])
print(iris)

     sepal_length  copy_sepal_width  sepal_width  petal_length  petal_width  \
0             5.1               3.5          3.5           1.4          0.2
1             4.9               3.0          3.0           1.4          0.2
2             4.7               3.2          3.2           1.3          0.2
3             4.6               3.1          3.1           1.5          0.2
4             5.0               3.6          3.6           1.4          0.2
..            ...               ...          ...           ...          ...
145           6.7               3.0          3.0           5.2          2.3
146           6.3               2.5          2.5           5.0          1.9
147           6.5               3.0          3.0           5.2          2.0
148           6.2               3.4          3.4           5.4          2.3
149           5.9               3.0          3.0           5.1          1.8

            species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [59]:
# delete the column 
del iris['copy_sepal_width']

```
> Data operations 
```

In [60]:
print(iris.sort_values(by='sepal_width'))

     sepal_length  sepal_width  petal_length  petal_width          species
60            5.0          2.0           3.5          1.0  Iris-versicolor
62            6.0          2.2           4.0          1.0  Iris-versicolor
119           6.0          2.2           5.0          1.5   Iris-virginica
68            6.2          2.2           4.5          1.5  Iris-versicolor
41            4.5          2.3           1.3          0.3      Iris-setosa
..            ...          ...           ...          ...              ...
16            5.4          3.9           1.3          0.4      Iris-setosa
14            5.8          4.0           1.2          0.2      Iris-setosa
32            5.2          4.1           1.5          0.1      Iris-setosa
33            5.5          4.2           1.4          0.2      Iris-setosa
15            5.7          4.4           1.5          0.4      Iris-setosa

[150 rows x 5 columns]

In [61]:
print(iris['sepal_width'].mean())

3.0540000000000003

In [62]:
print(iris['sepal_width'].sum())

458.1

#### There are a huge list of functions already implemented in `pandas` - see Documentation: https://pandas.pydata.org/pandas-docs/version/0.25/

---
---
## Your 7. Task
The file `annual_precip.csv` contains the average yearly rainfall and total land area for all the countries in the world. Load the data with the `pandas.read_csv` function of pandas, making sure that the names of the countries can be used to select a row, and perform the following tasks:
```
> Print the first 5 lines of the DataFrame to the screen with the .head() function.
> Print the average annual rainfall for Panama and make sure to include the units.
> Report the total land area of the Netherlands and make sure to include the units.
> Report all countries with an average annual rainfall less than 200 mm/year
> Report all countries with an average annual rainfall more than 2500 mm/year
> Report all countries with an average annual rainfall that is within 50 mm/year of the average annual rainfall in the Netherlands
```

                precip    area
country
Afghanistan      327.0   652.2
Albania         1485.0    27.4
Algeria           89.0  2381.7
American Samoa     NaN     0.2
Andorra            NaN     0.5

2692.0 mm/year

33.7 km^2

                      precip    area
country
Algeria                 89.0  2381.7
Bahrain                 83.0     0.8
Egypt, Arab Rep.        51.0   995.5
Jordan                 111.0    88.8
Kuwait                 121.0    17.8
Libya                   56.0  1759.5
Mauritania              92.0  1030.7
Niger                  151.0  1266.7
Oman                   125.0   309.5
Qatar                   74.0    11.6
Saudi Arabia            59.0  2149.7
Turkmenistan           161.0   469.9
United Arab Emirates    78.0    83.6
Yemen, Rep.            167.0   528.0

                       precip    area
country
Bangladesh             2666.0   130.2
Brunei Darussalam      2722.0     5.3
Colombia               2612.0  1109.5
Costa Rica             2926.0    51.1
Fiji                   2592.0    18.3
Indonesia              2702.0  1811.6
Malaysia               2875.0   328.6
Panama                 2692.0    74.3
Papua New Guinea       3142.0   452.9
Sao Tome and Principe  3200.0     1.0
Sierra Leone           2526.0    71.6
Solomon Islands        3028.0    28.0

                 precip    area
country
Burkina Faso      748.0   273.6
Lesotho           788.0    30.4
Mexico            752.0  1944.0
Netherlands       778.0    33.7
Slovak Republic   824.0    48.1
Swaziland         788.0    17.2

---